service:
  name: kaskadi-webhooks-tracking-lambda

package:
  individually: true
  exclude:
    - "**/**"

provider:
  name: aws
  runtime: nodejs10.x
  stackName: ${self:service.name}-stack
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'eu-central-1'}
  deploymentBucket:
    name: ${env:SLS_DEPLOY_BUCKET}
  deploymentPrefix: '@kaskadi/${self:service.name}'
  apiGateway:
    restApiId: !ImportValue KaskadiWebhooksRestAPIGatewayId
    restApiRootResourceId: !ImportValue KaskadiWebhooksRestAPIGatewayRootResourceId

functions:
  testLambda:
    handler: kaskadi-webhooks-tracking-lambda.handler
    name: ${self:service.name}
    package:
      include:
        - 'kaskadi-webhooks-tracking-lambda.js'
        - 'node_modules/**'
    environment:
      ES_ACCESS_ID: ${env:ES_ACCESS_ID}
      ES_ACCESS_SECRET: ${env:ES_ACCESS_SECRET}
      YSWS_TOKEN: ${env:YSWS_TOKEN}
    events:
      - http:
          method: post
          path: tracking
          cors: true
